import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const uiRoot = path.resolve(__dirname, '..');
const generatedPath = path.join(uiRoot, 'types', 'generated.ts');

const typeMappings = [
  { schema: 'RunListItem', alias: 'Run' },
  { schema: 'AgentSchema', alias: 'Agent' },
  { schema: 'PostSchema', alias: 'Post' },
  { schema: 'FeedSchema', alias: 'Feed' },
  { schema: 'AgentActionSchema', alias: 'AgentAction' },
  { schema: 'TurnSchema', alias: 'Turn' },
  { schema: 'FeedAlgorithmSchema', alias: 'FeedAlgorithm' },
  { schema: 'MetricSchema', alias: 'Metric' },
];

const lines: string[] = [
  '/**',
  ' * This file is automatically generated by scripts/generate-ui-contracts.mts.',
  ' * Do not edit this file directly; rerun npm run generate:api to regenerate.',
  ' */',
  '',
  "import type { components } from './api.generated';",
  '',
  '// Helpers',
  '',
  'type Primitive = string | number | boolean | bigint | symbol | null | undefined;',
  '',
  'type SnakeToCamelCase<S extends string> = S extends `${infer Head}_${infer Tail}`',
  '  ? `${Head}${Capitalize<SnakeToCamelCase<Tail>>}`',
  '  : S;',
  '',
  'type CamelizeObject<T> = T extends object',
  '  ? {',
  '      [K in keyof T as K extends string ? SnakeToCamelCase<K> : K]: Camelize<T[K]>;',
  '    }',
  '  : T;',
  '',
  'type CamelizeArray<T> = T extends readonly [infer Head, ...infer Tail]',
  '  ? [Camelize<Head>, ...CamelizeArray<Tail>]',
  '  : T extends readonly (infer Item)[]',
  '  ? Camelize<Item>[]',
  '  : T;',
  '',
  'type Camelize<T> = T extends Primitive',
  '  ? T',
  '  : T extends readonly unknown[]',
  '  ? CamelizeArray<T>',
  '  : CamelizeObject<T>;',
  '',
];

for (const { schema, alias } of typeMappings) {
  lines.push(`export type ${alias} = Camelize<components['schemas']['${schema}']>;`);
}

lines.push(
  '',
  "export type RunConfigBase = Camelize<components['schemas']['RunConfigDetail']>;",
  "export type RunConfig = Omit<RunConfigBase, 'metricKeys'> & {",
  '  metricKeys?: string[];',
  "  feedAlgorithmConfig: Record<string, unknown> | null;",
  '};',
  'export type RunConfigDetail = RunConfigBase;',
);

const fileContent = lines.join('\n');

fs.mkdirSync(path.dirname(generatedPath), { recursive: true });
fs.writeFileSync(generatedPath, fileContent, 'utf8');
console.log('Generated UI contract aliases at ui/types/generated.ts');
