"""initial schema

Revision ID: ba8d350bb2fd
Revises: 
Create Date: 2026-02-02 13:22:54.043121

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ba8d350bb2fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_bios',
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('generated_bio', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('handle')
    )
    op.create_table('bluesky_feed_posts',
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('author_display_name', sa.Text(), nullable=False),
    sa.Column('author_handle', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('quote_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uri')
    )
    with op.batch_alter_table('bluesky_feed_posts', schema=None) as batch_op:
        batch_op.create_index('idx_bluesky_feed_posts_author_handle', ['author_handle'], unique=False)

    op.create_table('bluesky_profiles',
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('did', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('follows_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('handle')
    )
    op.create_table('generated_feeds',
    sa.Column('feed_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('agent_handle', sa.Text(), nullable=False),
    sa.Column('post_uris', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('agent_handle', 'run_id', 'turn_number', name='pk_generated_feeds')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_agents', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.CheckConstraint("((status = 'completed' AND completed_at IS NOT NULL AND completed_at >= started_at) OR (status != 'completed' AND completed_at IS NULL))", name='ck_runs_completed_at_consistent'),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_runs_status_valid'),
    sa.CheckConstraint('total_agents > 0', name='ck_runs_total_agents_gt_0'),
    sa.CheckConstraint('total_turns > 0', name='ck_runs_total_turns_gt_0'),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(
            'idx_runs_created_at',
            [sa.column('created_at').desc()],
            unique=False,
        )
        batch_op.create_index('idx_runs_status', ['status'], unique=False)

    op.create_table('turn_metadata',
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('total_actions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint('turn_number >= 0', name='ck_turn_metadata_turn_number_gte_0'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name='fk_turn_metadata_run_id'),
    sa.PrimaryKeyConstraint('run_id', 'turn_number', name='pk_turn_metadata')
    )
    with op.batch_alter_table('turn_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_turn_metadata_run_id', ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_turn_metadata_run_id')

    op.drop_table('turn_metadata')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('idx_runs_status')
        batch_op.drop_index('idx_runs_created_at')

    op.drop_table('runs')
    op.drop_table('generated_feeds')
    op.drop_table('bluesky_profiles')
    with op.batch_alter_table('bluesky_feed_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_bluesky_feed_posts_author_handle')

    op.drop_table('bluesky_feed_posts')
    op.drop_table('agent_bios')
    # ### end Alembic commands ###
