/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint. Returns 200 when the service is up.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List simulation agents
         * @description Return simulation agent profiles from DB for View agents and Create form.
         */
        get: operations["get_simulation_agents_v1_simulations_agents_get"];
        put?: never;
        /**
         * Create simulation agent
         * @description Create a user-generated agent.
         */
        post: operations["post_simulation_agents_v1_simulations_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/agents/mock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List mock simulation agents
         * @description Return dummy agent list for run-detail context (mock runs).
         */
        get: operations["get_simulation_agents_mock_v1_simulations_agents_mock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/config/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get default simulation config
         * @description Return default config for simulation start form (num_agents, num_turns).
         */
        get: operations["get_simulation_config_default_v1_simulations_config_default_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/feed-algorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List feed algorithms
         * @description Return available feed algorithms with metadata for the UI.
         */
        get: operations["get_simulation_feed_algorithms_v1_simulations_feed_algorithms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List metrics
         * @description Return available metrics with metadata for the UI.
         */
        get: operations["get_simulation_metrics_v1_simulations_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List simulation posts
         * @description Return posts, optionally filtered by URIs. Batch lookup for feed resolution.
         */
        get: operations["get_simulation_posts_v1_simulations_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a simulation
         * @description Execute a synchronous simulation run.
         */
        post: operations["post_simulations_run_v1_simulations_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List simulation runs
         * @description Return simulation run summaries for the UI.
         */
        get: operations["get_simulation_runs_v1_simulations_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get simulation run details
         * @description Fetch run config and turn-by-turn action summary by run ID.
         */
        get: operations["get_simulation_run_v1_simulations_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/runs/{run_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get simulation run turns
         * @description Return full per-turn payload for a run ID.
         */
        get: operations["get_simulation_run_turns_v1_simulations_runs__run_id__turns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentActionSchema
         * @description Action event performed by an agent in a turn.
         */
        AgentActionSchema: {
            /** Action Id */
            action_id: string;
            /** Agent Handle */
            agent_handle: string;
            /** Created At */
            created_at: string;
            /** Post Uri */
            post_uri?: string | null;
            type: components["schemas"]["TurnAction"];
            /** User Id */
            user_id?: string | null;
        };
        /**
         * AgentSchema
         * @description Agent profile for the simulation UI.
         */
        AgentSchema: {
            /** Bio */
            bio: string;
            /** Followers */
            followers: number;
            /** Following */
            following: number;
            /** Generated Bio */
            generated_bio: string;
            /** Handle */
            handle: string;
            /** Name */
            name: string;
            /** Posts Count */
            posts_count: number;
        };
        /**
         * CreateAgentRequest
         * @description Request body for POST /v1/simulations/agents.
         *
         *     Fast-follows (not yet supported):
         *     - comments: list of {text, postUri}
         *     - likedPostUris: list of post URIs
         *     - linkedAgentHandles: list of agent handles to link
         */
        CreateAgentRequest: {
            /**
             * Bio
             * @default
             */
            bio: string;
            /** Display Name */
            display_name: string;
            /** Handle */
            handle: string;
        };
        /**
         * DefaultConfigSchema
         * @description Default config for simulation start form.
         */
        DefaultConfigSchema: {
            /** Num Agents */
            num_agents: number;
            /** Num Turns */
            num_turns: number;
        };
        /**
         * ErrorDetail
         * @description Error payload included when status is failed or on server error.
         */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Message */
            message: string;
        };
        /**
         * FeedAlgorithmSchema
         * @description API response for GET /v1/simulations/feed-algorithms.
         */
        FeedAlgorithmSchema: {
            /** Config Schema */
            config_schema?: {
                [key: string]: unknown;
            } | null;
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
        };
        /**
         * FeedSchema
         * @description Feed metadata for one agent in a turn.
         */
        FeedSchema: {
            /** Agent Handle */
            agent_handle: string;
            /** Created At */
            created_at: string;
            /** Feed Id */
            feed_id: string;
            /** Post Uris */
            post_uris: string[];
            /** Run Id */
            run_id: string;
            /** Turn Number */
            turn_number: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /**
         * MetricSchema
         * @description API response for GET /v1/simulations/metrics.
         */
        MetricSchema: {
            /** Author */
            author: string;
            /** Description */
            description: string;
            /** Key */
            key: string;
            scope: components["schemas"]["MetricScope"];
        };
        /**
         * MetricScope
         * @enum {string}
         */
        MetricScope: "turn" | "run";
        /**
         * PostSchema
         * @description Post content for display in agent feeds. Matches ApiPost in ui/lib/api/simulation.ts.
         */
        PostSchema: {
            /** Author Display Name */
            author_display_name: string;
            /** Author Handle */
            author_handle: string;
            /** Bookmark Count */
            bookmark_count: number;
            /** Created At */
            created_at: string;
            /** Like Count */
            like_count: number;
            /** Quote Count */
            quote_count: number;
            /** Reply Count */
            reply_count: number;
            /** Repost Count */
            repost_count: number;
            /** Text */
            text: string;
            /** Uri */
            uri: string;
        };
        /**
         * RunConfigDetail
         * @description Configuration for a persisted run.
         */
        RunConfigDetail: {
            /** Feed Algorithm */
            feed_algorithm: string;
            /** Num Agents */
            num_agents: number;
            /** Num Turns */
            num_turns: number;
        };
        /**
         * RunDetailsResponse
         * @description Response body for GET /v1/simulations/runs/{run_id}.
         */
        RunDetailsResponse: {
            /** Completed At */
            completed_at?: string | null;
            config: components["schemas"]["RunConfigDetail"];
            /** Created At */
            created_at: string;
            /** Run Id */
            run_id: string;
            /** Run Metrics */
            run_metrics?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Started At */
            started_at: string;
            status: components["schemas"]["RunStatus"];
            /** Turns */
            turns: components["schemas"]["TurnActionsItem"][];
        };
        /**
         * RunListItem
         * @description Summary item for listing simulation runs.
         */
        RunListItem: {
            /** Created At */
            created_at: string;
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Total Agents */
            total_agents: number;
            /** Total Turns */
            total_turns: number;
        };
        /**
         * RunRequest
         * @description Request body for POST /v1/simulations/run.
         */
        RunRequest: {
            /** Feed Algorithm */
            feed_algorithm?: string | null;
            /** Feed Algorithm Config */
            feed_algorithm_config?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Num Agents */
            num_agents: number;
            /** Num Turns */
            num_turns?: number | null;
        };
        /**
         * RunResponse
         * @description Response body for POST /v1/simulations/run.
         */
        RunResponse: {
            /** Created At */
            created_at: string;
            error?: components["schemas"]["ErrorDetail"] | null;
            /** Num Agents */
            num_agents: number;
            /** Num Turns */
            num_turns: number;
            /** Run Id */
            run_id: string;
            /** Run Metrics */
            run_metrics?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            status: components["schemas"]["RunResponseStatus"];
            /** Turns */
            turns: components["schemas"]["TurnSummaryItem"][];
        };
        /**
         * RunResponseStatus
         * @description Status of a simulation run as returned by the API.
         * @enum {string}
         */
        RunResponseStatus: "completed" | "failed";
        /**
         * RunStatus
         * @description Enum representing the state of a simulation run.
         *
         *     State transitions:
         *       - RUNNING: The run is actively in progress. All runs start in this state.
         *       - COMPLETED: The run has finished successfully. Set when the simulation
         *         completes all turns and agents have completed their actions.
         *       - FAILED: The run has terminated abnormally due to an error or interruption.
         *         No further progress will be made.
         *
         *     Valid transitions:
         *       - RUNNING -> COMPLETED: Normal successful completion.
         *       - RUNNING -> FAILED: Error or failure during simulation.
         * @enum {string}
         */
        RunStatus: "running" | "completed" | "failed";
        /**
         * TurnAction
         * @description Action types for a simulation turn.
         * @enum {string}
         */
        TurnAction: "like" | "comment" | "follow";
        /**
         * TurnActionsItem
         * @description One turn summary with aggregate action counts.
         */
        TurnActionsItem: {
            /** Created At */
            created_at: string;
            /** Metrics */
            metrics?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Total Actions */
            total_actions: {
                [key: string]: number;
            };
            /** Turn Number */
            turn_number: number;
        };
        /**
         * TurnSchema
         * @description Full turn payload consumed by the UI.
         */
        TurnSchema: {
            /** Agent Actions */
            agent_actions: {
                [key: string]: components["schemas"]["AgentActionSchema"][];
            };
            /** Agent Feeds */
            agent_feeds: {
                [key: string]: components["schemas"]["FeedSchema"];
            };
            /** Turn Number */
            turn_number: number;
        };
        /**
         * TurnSummaryItem
         * @description One turn summary with computed metrics.
         */
        TurnSummaryItem: {
            /** Created At */
            created_at: string;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Total Actions */
            total_actions: {
                [key: string]: number;
            };
            /** Turn Number */
            turn_number: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_simulation_agents_v1_simulations_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSchema"][];
                };
            };
        };
    };
    post_simulation_agents_v1_simulations_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_agents_mock_v1_simulations_agents_mock_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentSchema"][];
                };
            };
        };
    };
    get_simulation_config_default_v1_simulations_config_default_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultConfigSchema"];
                };
            };
        };
    };
    get_simulation_feed_algorithms_v1_simulations_feed_algorithms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedAlgorithmSchema"][];
                };
            };
        };
    };
    get_simulation_metrics_v1_simulations_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSchema"][];
                };
            };
        };
    };
    get_simulation_posts_v1_simulations_posts_get: {
        parameters: {
            query?: {
                /** @description Filter by post URIs */
                uris?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_simulations_run_v1_simulations_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_runs_v1_simulations_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListItem"][];
                };
            };
        };
    };
    get_simulation_run_v1_simulations_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_run_turns_v1_simulations_runs__run_id__turns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["TurnSchema"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
