/**
 * This file is automatically generated by scripts/generate-ui-contracts.mts.
 * Do not edit this file directly; rerun npm run generate:api to regenerate.
 */

import type { components } from './api.generated';

// Helpers

type Primitive = string | number | boolean | bigint | symbol | null | undefined;

type SnakeToCamelCase<S extends string> = S extends `${infer Head}_${infer Tail}`
  ? `${Head}${Capitalize<SnakeToCamelCase<Tail>>}`
  : S;

type CamelizeObject<T> = T extends object
  ? {
      [K in keyof T as K extends string ? SnakeToCamelCase<K> : K]: Camelize<T[K]>;
    }
  : T;

type CamelizeArray<T> = T extends readonly [infer Head, ...infer Tail]
  ? [Camelize<Head>, ...CamelizeArray<Tail>]
  : T extends readonly (infer Item)[]
  ? Camelize<Item>[]
  : T;

type Camelize<T> = T extends Primitive
  ? T
  : T extends readonly any[]
  ? CamelizeArray<T>
  : CamelizeObject<T>;

export type Run = Camelize<components['schemas']['RunListItem']>;
export type Agent = Camelize<components['schemas']['AgentSchema']>;
export type Post = Camelize<components['schemas']['PostSchema']>;
export type Feed = Camelize<components['schemas']['FeedSchema']>;
export type AgentAction = Camelize<components['schemas']['AgentActionSchema']>;
export type Turn = Camelize<components['schemas']['TurnSchema']>;
export type FeedAlgorithm = Camelize<components['schemas']['FeedAlgorithmSchema']>;
export type Metric = Camelize<components['schemas']['MetricSchema']>;

export type RunConfigBase = Camelize<components['schemas']['RunConfigDetail']>;
export type RunConfig = Omit<RunConfigBase, 'metricKeys'> & {
  metricKeys?: string[];
  feedAlgorithmConfig: Record<string, unknown> | null;
};
export type RunConfigDetail = RunConfigBase;