/**
 * UI-friendly aliases for backend schemas generated by scripts/generate-ui-contracts.mts.
 * Re-run `npm run generate:api` to refresh this file whenever the OpenAPI spec changes.
 */
export type Run = import('./generated').Run;
export type Agent = import('./generated').Agent;
export type Post = import('./generated').Post;
export type Feed = import('./generated').Feed;
export type AgentAction = import('./generated').AgentAction;
export type Turn = import('./generated').Turn;
export type FeedAlgorithm = import('./generated').FeedAlgorithm;
export type Metric = import('./generated').Metric;
export type RunConfig = import('./generated').RunConfig;

/**
 * Structured API error from backend. Backend uses { error: { code, message, detail } }.
 * Thrown by fetchJson on non-2xx responses.
 */
export class ApiError extends Error {
  readonly code: string;
  readonly message: string;
  readonly detail: string | null;
  readonly status: number;

  constructor(code: string, message: string, detail: string | null, status: number) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
    this.message = message;
    this.detail = detail;
    this.status = status;
    Object.setPrototypeOf(this, ApiError.prototype);
  }
}
